In [1]:
import numpy as np

In [2]:
my_3d_array = np.arange(70)

In [3]:
my_3d_array.shape=(2,7,5)

In [4]:
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [5]:
my_3d_array.shape

(2, 7, 5)

In [6]:
my_3d_array.ndim# the dimension


3

In [7]:
my_3d_array.size

70

In [8]:
my_3d_array.dtype

dtype('int32')

In [9]:
5*my_3d_array-1

array([[[ -1,   4,   9,  14,  19],
        [ 24,  29,  34,  39,  44],
        [ 49,  54,  59,  64,  69],
        [ 74,  79,  84,  89,  94],
        [ 99, 104, 109, 114, 119],
        [124, 129, 134, 139, 144],
        [149, 154, 159, 164, 169]],

       [[174, 179, 184, 189, 194],
        [199, 204, 209, 214, 219],
        [224, 229, 234, 239, 244],
        [249, 254, 259, 264, 269],
        [274, 279, 284, 289, 294],
        [299, 304, 309, 314, 319],
        [324, 329, 334, 339, 344]]])

In [12]:
left_mat=np.arange(6).reshape((2,3))
right_mat=np.arange(15).reshape((3,5))

In [13]:
left_mat


array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
right_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
np.inner(left_mat, right_mat)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [17]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

###Operations along axes

In [21]:
my_3d_array.shape

(2, 7, 5)

In [23]:
my_3d_array.sum()

2415

In [25]:
(69*70)/2#(N*N-1)/2

2415.0

In [29]:
my_3d_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [30]:
my_3d_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [31]:
my_3d_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

###Broadcasting rules

In [33]:
my_2d_array=np.ones(35,dtype='int_').reshape((7,5))*3
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [42]:
my_random_2d=np.random.random((7,5))

In [43]:
np.set_printoptions(precision=4)

In [44]:
my_3d_array*my_random_2d

array([[[ 0.    ,  0.479 ,  1.9348,  2.6589,  1.3916],
        [ 4.8836,  3.8746,  6.1163,  5.999 ,  2.3052],
        [ 6.774 ,  0.3944,  1.1259,  5.7996,  3.8515],
        [ 8.1704, 11.5295, 13.7048,  8.0949, 17.1013],
        [ 2.6497,  6.21  ,  6.107 ,  7.3345, 15.6105],
        [12.7129,  3.5995, 19.4262,  9.3528, 12.1499],
        [ 4.1971, 17.9698, 30.2482,  6.1054, 33.6232]],

       [[31.5189, 17.243 , 35.7945, 33.6797, 13.5683],
        [39.0685, 26.4766, 36.698 , 32.2445, 11.2699],
        [30.4832,  1.6493,  4.4099, 21.4139, 13.4801],
        [27.2345, 36.7502, 41.9205, 23.835 , 48.6036],
        [ 7.2868, 16.56  , 15.8228, 18.4956, 38.3758],
        [30.511 ,  8.4449, 44.6083, 21.0437, 26.8137],
        [ 9.0936, 38.2582, 63.3321, 12.5808, 68.2353]]])

In [49]:
my_vector=np.arange(5)*7
my_vector[0]=1
my_vector

array([ 1,  7, 14, 21, 28])

In [50]:
my_3d_array/my_vector

array([[[ 0.    ,  0.1429,  0.1429,  0.1429,  0.1429],
        [ 5.    ,  0.8571,  0.5   ,  0.381 ,  0.3214],
        [10.    ,  1.5714,  0.8571,  0.619 ,  0.5   ],
        [15.    ,  2.2857,  1.2143,  0.8571,  0.6786],
        [20.    ,  3.    ,  1.5714,  1.0952,  0.8571],
        [25.    ,  3.7143,  1.9286,  1.3333,  1.0357],
        [30.    ,  4.4286,  2.2857,  1.5714,  1.2143]],

       [[35.    ,  5.1429,  2.6429,  1.8095,  1.3929],
        [40.    ,  5.8571,  3.    ,  2.0476,  1.5714],
        [45.    ,  6.5714,  3.3571,  2.2857,  1.75  ],
        [50.    ,  7.2857,  3.7143,  2.5238,  1.9286],
        [55.    ,  8.    ,  4.0714,  2.7619,  2.1071],
        [60.    ,  8.7143,  4.4286,  3.    ,  2.2857],
        [65.    ,  9.4286,  4.7857,  3.2381,  2.4643]]])