In [10]:
import numpy as np

In [4]:
print(np.__version__)

1.16.0


In [5]:
my_list=[-17,3,3,2,5]

In [6]:
my_list

[-17, 3, 3, 2, 5]

In [18]:
my_array_from_list = np.array(my_list)

In [19]:
my_array_from_list*10

array([-170,   30,   30,   20,   50])

In [20]:
my_tuple=(14,-3,4)
np.array(my_tuple)

array([14, -3,  4])

In [21]:
my_tuple*2


(14, -3, 4, 14, -3, 4)

In [22]:
arange(7)

NameError: name 'arange' is not defined

In [23]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
np.arange(10,23,2)

array([10, 12, 14, 16, 18, 20, 22])

In [28]:
np.arange(10,23,2)-1

array([ 9, 11, 13, 15, 17, 19, 21])

In [29]:
len(my_array_from_list)

5

In [30]:
my_array_from_list.size

5

In [34]:
np.linspace(2,5,7)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [35]:
my_vestor= np.array([2,34,4,34,3,3])

In [36]:
my_vestor[0]=3

In [37]:
my_vestor

array([ 3, 34,  4, 34,  3,  3])

In [41]:
my_array=np.arange(35)
my_array.shape = (7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [42]:
my_array[2]

array([10, 11, 12, 13, 14])

In [43]:
my_array[-2]

array([25, 26, 27, 28, 29])

In [44]:
my_array[2,3]

13

In [45]:
my_array[5][2]

27

In [47]:
my_3d=np.arange(70)
my_3d.shape = (2,7,5)
my_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [51]:
my_3d[0][1][1]=1111

In [52]:
my_3d

array([[[   0,    1,    2,    3,    4],
        [   5, 1111,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51,   52,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

In [53]:
Zero_mod=0==(my_3d%7)

In [54]:
Zero_mod


array([[[ True, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False,  True, False, False, False],
        [False, False, False,  True, False],
        [False, False, False, False, False]],

       [[ True, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False,  True, False, False, False],
        [False, False, False,  True, False],
        [False, False, False, False, False]]])

In [55]:
sub_array=my_3d[Zero_mod]
sub_array

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63])

In [56]:
sub_array[sub_array>6]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

In [57]:
sub_array


array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63])

In [58]:
mod_test=0==(my_vestor%7)

In [59]:
mod_test


array([False, False, False, False, False, False])

In [60]:
positive_test=my_3d>0
positive_test

array([[[False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [63]:
combined_test=np.logical_and(Zero_mod,positive_test)

In [65]:
combined_test

array([[[False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False,  True, False, False, False],
        [False, False, False,  True, False],
        [False, False, False, False, False]],

       [[ True, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False,  True, False, False, False],
        [False, False, False,  True, False],
        [False, False, False, False, False]]])

In [66]:
my_3d[combined_test]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])